"""preserving refrential integrity

Revision ID: 2d07c34e5be3
Revises: fc69d4a7856a
Create Date: 2022-08-14 10:02:03.422651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d07c34e5be3'
down_revision = 'fc69d4a7856a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('artists_genres_genre_id_fkey', 'artists_genres', type_='foreignkey')
    op.drop_constraint('artists_genres_artist_id_fkey', 'artists_genres', type_='foreignkey')
    op.create_foreign_key(None, 'artists_genres', 'artists', ['artist_id'], ['artist_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'artists_genres', 'genres', ['genre_id'], ['genre_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('shows_venue_id_fkey', 'shows', type_='foreignkey')
    op.drop_constraint('shows_artist_id_fkey', 'shows', type_='foreignkey')
    op.create_foreign_key(None, 'shows', 'artists', ['artist_id'], ['artist_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'shows', 'venues', ['venue_id'], ['venue_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('venues_genres_venue_id_fkey', 'venues_genres', type_='foreignkey')
    op.drop_constraint('venues_genres_genre_id_fkey', 'venues_genres', type_='foreignkey')
    op.create_foreign_key(None, 'venues_genres', 'genres', ['genre_id'], ['genre_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'venues_genres', 'venues', ['venue_id'], ['venue_id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venues_genres', type_='foreignkey')
    op.drop_constraint(None, 'venues_genres', type_='foreignkey')
    op.create_foreign_key('venues_genres_genre_id_fkey', 'venues_genres', 'genres', ['genre_id'], ['genre_id'])
    op.create_foreign_key('venues_genres_venue_id_fkey', 'venues_genres', 'venues', ['venue_id'], ['venue_id'])
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.create_foreign_key('shows_artist_id_fkey', 'shows', 'artists', ['artist_id'], ['artist_id'])
    op.create_foreign_key('shows_venue_id_fkey', 'shows', 'venues', ['venue_id'], ['venue_id'])
    op.drop_constraint(None, 'artists_genres', type_='foreignkey')
    op.drop_constraint(None, 'artists_genres', type_='foreignkey')
    op.create_foreign_key('artists_genres_artist_id_fkey', 'artists_genres', 'artists', ['artist_id'], ['artist_id'])
    op.create_foreign_key('artists_genres_genre_id_fkey', 'artists_genres', 'genres', ['genre_id'], ['genre_id'])
    # ### end Alembic commands ###
