"""changing primary keys of linking tables

Revision ID: fc69d4a7856a
Revises: d79c4ead64f1
Create Date: 2022-08-13 23:52:32.192026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc69d4a7856a'
down_revision = 'd79c4ead64f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists_genres', 'artists_genres_id')
    op.drop_column('venues_genres', 'venues_genres_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues_genres', sa.Column('venues_genres_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('artists_genres', sa.Column('artists_genres_id', sa.INTEGER(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###
